name: Build and Release Python Wheel
on:
  push:
    branches:
      - master
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Read version
        id: read_version
        run: echo -n "version=$(poetry version --short)" >> $GITHUB_OUTPUT
      - name: Test
        run: echo ${{ steps.read_version.outputs.outputs.version }}
      - name: Build python package
        run: |
          poetry build
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v{{ steps.read_version.outputs.outputs.version }}
          release_name: Release of version {{ steps.read_version.outputs.outputs.version }}
          draft: true
          prerelease: true
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/dist/weba_odoo_tasks_management_bot-{{ steps.read_version.outputs.outputs.version }}-py3-none-any.whl
          asset_name: weba_odoo_tasks_management_bot-{{ steps.read_version.outputs.outputs.version }}-py3-none-any.whl
          asset_content_type: application/zip
